# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AmazingMazes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmazingMazes
  pod 'Alamofire', '~> 4.6'
  pod 'SDWebImage', '~> 4.0'
  pod 'ImageScrollView'

end
